/* 各工序预警开发学习 */
--查询数据库：KBLIVE 中 用户自定义  数据表 主要看建表时间
select * from sysobjects where xtype='U' ORDER BY CRDATE DESC

--预警:
select * from WN_DATA0001 order by ENT_DATE

--预警:解决方案
/*37 条数据*/
select * from WN_DATA0002

/*方便直观查看具体预警信息*/
--存储过程   WN_INFO
SELECT d1.PART_NUMBER,d1.CUST_NAME,d2.POSITION,d1.ENT_DATE,d1.CREATED_USER_PTR,d1.MODIFY_DATE,d1.PRODUCT_CHARACTER
,d1.PRODUCT_CHARACTER,d2.PRODUCT_WARNING_CHARACTER,d2.WARNING_SOLUTION
FROM WN_DATA0001  d1 left join WN_DATA0002 d2 
on d2.WN_DATA0001_PTR=d1.RKEY
order by d1.MODIFY_DATE DESC

PRODUCT_CHARACTER	
FRONT_DEPT_TIMES	
RKEY	
WN_DATA0001_PTR	
PRODUCT_WARNING_CHARACTER	
POSITION	WARNING_SOLUTION


--预警:各工序人员
SELECT * FROM 工序品质预警$

SELECT * FROM WN_DATA0008
SELECT * FROM WN_DATA0007
SELECT * FROM WN_DATA0006
SELECT * FROM WN_DATA0005
SELECT * FROM WN_DATA0004
SELECT * FROM WN_DATA0003
SELECT * FROM WN_DATA0002
SELECT * FROM WN_DATA0001